# Built-in 6-axis intertial measurement unit (IMU) that also includes a temperature sensor
- platform: mpu6886
  i2c_id: internal_bus_a
  address: 0x68
  update_interval: 10s
  accel_x:
    name: "${friendly_name} MPU6886 Accel X"
  accel_y:
    name: "${friendly_name} MPU6886 Accel Y"
  accel_z:
    name: "${friendly_name} MPU6886 Accel z"
  gyro_x:
    name: "${friendly_name} MPU6886 Gyro X"
  gyro_y:
    name: "${friendly_name} MPU6886 Gyro Y"
  gyro_z:
    name: "${friendly_name} MPU6886 Gyro z"
  temperature:
    name: "${friendly_name} MPU6886 Temperature"
