# https://esphome.io/components/switch/template.html
- platform: template
  name: "${friendly_name} Motor Active Switch"
  id: motor_active_switch
  icon: "mdi:bell-ring"
  optimistic: true
  assumed_state: true
  # https://esphome.io/components/switch/
  restore_mode: RESTORE_DEFAULT_OFF
  turn_on_action:
    - script.execute:
        id: turn_on_atom_motor_active_light
        delay_ms: 1
  turn_off_action:
    - light.turn_off: atom_light
