# Still want to convert to ethernet at some point
# pattern for naming
substitutions:
  node_name: devfbsmellsensorv2
  friendly_name: Dev Full Bath Smell Sensor V2
  area: Full Bath
  comment: "This is for developing a proper methane sensor"
  box_config_file_name: dev_full_bath_smell_sensor_v2

packages:
  esphome: !include common/default_esphome.yaml
  logging: !include common/verbose_logger.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atom_device.yaml
  light: !include { file: common/atom_light.yaml, vars: { light_pin: 27 } }
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml
  i2c: !include common/default_i2c.yaml
  button: !include { file: common/default_atom_button.yaml, vars: { button_pin: 39 } }
  smell_sensor: !include common/smell_sensor.yaml
