# https://www.reddit.com/r/homeassistant/comments/rm71z4/lilygo_t5_epaper_display_now_using_esphome/
# https://community.home-assistant.io/t/lilygo-t5-4-7-inch-e-paper-idiots-guide/407267/3
# https://github.com/esphome/feature-requests/issues/1109#issuecomment-986018421
# https://www.stdin.co.uk/blog2/2023/11/lilygo-t5-4.7-e-paper-display-esphome/
substitutions:
  node_name: devlilygoeinkdisplay
  friendly_name: Dev Lilygo E-Ink Display
  area: Dev
  comment: "This is for developing a decently sized E-Ink display at Albion"
  box_config_file_name: dev_lilygo_eink_display

esphome:
  name: ${node_name}
#  friendly_name: Paper1Screen
  area: ${area}
  comment: ${comment}
  project: !include common/default_project.yaml
  platformio_options:
    board_build.f_flash: 80000000L
    #board_upload.flash_size: 16MB
    board_build.flash_mode: qio
    board_build.psram_type: opi
    board_build.partitions: default_16MB.csv
    board_build.arduino.memory_type: qio_opi

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: 2.0.7
  flash_size: 16MB

packages:
#  esphome: !include common/default_esphome.yaml
#  esp32: !include common/m5atoms3lite_device.yaml
#  esp32: !include common/lilygot5display_device.yaml
  #  logging: !include common/s3_logger.yaml
  wifi: !include common/wifi.yaml
  logging: !include common/s3_debug_logger.yaml
#  light: !include { file: common/atom_light.yaml, vars: { light_pin: 27 } }
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml
  default_fonts: !include common/fonts.yaml
#  i2c: !include common/default_i2c.yaml
#  button: !include { file: common/default_atom_button.yaml, vars: { button_pin: 39 } }

i2c:
  sda: GPIO17
  scl: GPIO18
  # There is some problems with i2c scan so turn scan off if problem appear on your board
  scan: false
  id: bus_a

#external_components:
#  - source: github://nickolay/esphome-lilygo-t547plus
#    components: ["t547"]

external_components:
  - source: github://bvarick/esphome-lilygo-t547plus
    components: ["t547"]
#  - source: github://kaeltis/esphome-lilygo-t547plus
#    components: ["lilygo_t5_47_battery"]

text_sensor:
  - platform: homeassistant
    name: "Bart Next Train Antioch Status"
    entity_id: text.bart_next_train_antioch_status
    id: bart_next_train_antioch_status
    on_value:
      then:
        - lambda: |-
            ESP_LOGD("bart_next_train_antioch_sensor", "The current antioch sensor is %s", x.c_str());
        - component.update: t5_display
  - platform: homeassistant
    name: "Bart Next Train Berryessa Status"
    entity_id: text.bart_next_train_berryessa_status
    id: bart_next_train_berryessa_status
    on_value:
      then:
        - component.update: t5_display
  - platform: homeassistant
    name: "Bart Next Train Daly City Status"
    entity_id: text.bart_next_train_daly_city_status
    id: bart_next_train_daly_city_status
    on_value:
      then:
        - component.update: t5_display
  - platform: homeassistant
    name: "Bart Next Train Dublin/Pleasanton Status"
    entity_id: text.bart_next_train_dublin_pleasanton_status
    id: bart_next_train_dublin_pleasanton_status
    on_value:
      then:
        - component.update: t5_display
  - platform: homeassistant
    name: "Bart Next Train Millbrae Status"
    entity_id: text.bart_next_train_millbrae_status
    id: bart_next_train_millbrae_status
    on_value:
      then:
        - component.update: t5_display
  - platform: homeassistant
    name: "Bart Next Train Pittsburg/Bay Point Status"
    entity_id: text.bart_next_train_pittsburg_bay_point_status
    id: bart_next_train_pittsburg_bay_point_status
    on_value:
      then:
        - component.update: t5_display
  - platform: homeassistant
    name: "Bart Next Train Richmond Status"
    entity_id: text.bart_next_train_richmond_status
    id: bart_next_train_richmond_status
    on_value:
      then:
        - component.update: t5_display
  - platform: homeassistant
    name: "Bart Next Train SF Airport Status"
    entity_id: text.bart_next_train_sf_airport_status
    id: bart_next_train_sf_airport_status
    on_value:
      then:
        - component.update: t5_display
  - platform: homeassistant
    name: "Bart Next Train SFO/Millbrae Status"
    entity_id: text.bart_next_train_sfo_millbrae_status
    id: bart_next_train_sfo_millbrae_status
    on_value:
      then:
        - component.update: t5_display
  - platform: homeassistant
    name: "Bart Next Train 24th Street Status"
    entity_id: text.bart_next_train_24th_street_status
    id: bart_next_train_24th_street_status
    on_value:
      then:
        - component.update: t5_display

display:
  - platform: t547
    id: t5_display
    update_interval: 30s
    lambda: |-
      //ESP_LOGD("display", "got antioch state %s", id(bart_next_train_antioch_status).state);
      //ESP_LOGD("display", "got daly city state %s", id(bart_next_train_daly_city_status).state);
      //ESP_LOGD("display", "got antioch state to string %s", id(bart_next_train_antioch_status).state.c_str());
      //ESP_LOGD("display", "got daly city state to string %s", id(bart_next_train_daly_city_status).state.c_str());
      //ESP_LOGD("display", "got antioch numerical state %d", id(bart_next_train_antioch_status).state);
      //ESP_LOGD("display", "got daly city numerical state %d", id(bart_next_train_daly_city_status).state);
      it.printf(0, 0, id(my_font), "The next Antioch is: %s", id(bart_next_train_antioch_status).state.c_str());
      it.printf(0, 20, id(my_font), "The next Berryessa is: %s", id(bart_next_train_berryessa_status).state.c_str());
      it.printf(0, 40, id(my_font), "The next Daly City is: %s", id(bart_next_train_daly_city_status).state.c_str());
      it.printf(0, 60, id(my_font), "The next Dublin/Pleasanton is: %s", id(bart_next_train_dublin_pleasanton_status).state.c_str());
      it.printf(0, 80, id(my_font), "The next Millbrae is: %s", id(bart_next_train_millbrae_status).state.c_str());
      it.printf(0, 100, id(my_font), "The next Pittsburg/Bay Point is: %s", id(bart_next_train_pittsburg_bay_point_status).state.c_str());
      it.printf(0, 120, id(my_font), "The next Richmond is: %s", id(bart_next_train_richmond_status).state.c_str());
      it.printf(0, 140, id(my_font), "The next SF Airport is: %s", id(bart_next_train_sf_airport_status).state.c_str());
      it.printf(0, 160, id(my_font), "The next SFO/Millbrae is: %s", id(bart_next_train_sfo_millbrae_status).state.c_str());
      it.printf(0, 180, id(my_font), "The next 24th Street is: %s", id(bart_next_train_24th_street_status).state.c_str());
