substitutions:
  node_name: devjukeboxswitch
  friendly_name: Dev Jukebox Switch
  area: Dev
  comment: "This is a dev device for the jukebox functionality"
  box_config_file_name: dev_jukebox_switch
  relay_1_pin: GPIO22
  relay_2_pin: GPIO19

packages:
  esphome: !include common/default_esphome.yaml
#  logging: !include common/default_logger.yaml
  logging: !include common/debug_logger.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atom_device.yaml
  light: !include { file: common/atom_light.yaml, vars: { light_pin: 27 } }
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml
  button: !include { file: common/default_atom_button.yaml, vars: { button_pin: 39 } }

## Device-specific

# https://devices.esphome.io/devices/Generic-Relay
switch:
  - platform: gpio
    name: "${friendly_name} Relay 1"
    pin: ${relay_1_pin}
  - platform: gpio
    name: "${friendly_name} Relay 2"
    pin: ${relay_2_pin}
