substitutions:
  node_name: devlightstrip
  friendly_name: Dev Light Strip
  area: Dev
  comment: "This is the first dev device for using a simple LED strip"
  box_config_file_name: dev_light_strip
  light_strip_name: "RGBW"
  light_strip_id: "dev_light_strip"
  light_strip_rmt_channel: "0"
  light_strip_icon: "mdi:led-strip-variant"
#  light_strip_data_pin: "22"
  light_strip_data_pin: "26"
  light_strip_num_leds: "70"

packages:
  esphome: !include common/default_esphome.yaml
#  logging: !include common/default_logger.yaml
  logging: !include common/debug_logger.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atom_device.yaml
  light: !include { file: common/atom_light.yaml, vars: { light_pin: 27 } }
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml
  button: !include { file: common/default_atom_button.yaml, vars: { button_pin: 39 } }

light:
  - <<: !include { file: common/light_strip.yaml, vars: { led_strip_name: "${light_strip_name}", led_strip_id: "${light_strip_id}", light_data_pin: "${light_strip_data_pin}", rmt_channel: "${light_strip_rmt_channel}", led_strip_icon: "${light_strip_icon}",num_leds: "${light_strip_num_leds}" } }
