substitutions:
  node_name: devreedswitchsensor
  friendly_name: Dev Reed Switch Sensor Sensor
  area: Dev
  comment: "This is the first dev device for using a reed switch"
  box_config_file_name: dev_reed_switch_sensor

packages:
  esphome: !include common/default_esphome.yaml
#  logging: !include common/default_logger.yaml
  logging: !include common/debug_logger.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atom_device.yaml
  light: !include { file: common/atom_light.yaml, vars: { light_pin: 27 } }
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml
  i2c: !include common/default_i2c.yaml
  button: !include { file: common/default_atom_button.yaml, vars: { button_pin: 39 } }

binary_sensor:
  # Reports when the reed switch from GPIO04 to GND is sensing a magnet and the door is closed.
  - platform: gpio
    name: "${friendly_name} Reed Switch"
    pin:
      number: GPIO04
      mode: INPUT_PULLUP
      inverted: False
