# Uses the M5Stack Atom Socket
# https://shop.m5stack.com/products/atom-socket-kit-hlw8023-jp-us
# Socket pins:
# G22 - Rx
# G23 - Relay
substitutions:
  node_name: backhouselightsplug
  friendly_name: Back of House Lights Plug
  area: Back House
  comment: "This is the prototype for Burning Man simple lights control"
  box_config_file_name: playa_back_house_lights_plug
  relay_pin: GPIO23

packages:
  esphome: !include common/default_esphome.yaml
  logging: !include common/default_logger.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atom_device.yaml
  light: !include { file: common/atom_light.yaml, vars: { light_pin: 27 } }
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml
  button: !include { file: common/default_atom_button.yaml, vars: { button_pin: 39 } }

## Device-specific

# for power monitoring:
# * https://github.com/esphome/feature-requests/issues/1386
# * https://esphome.io/components/sensor/hlw8012.html
# * https://esphome.io/components/sensor/cse7766.html
# * https://community.home-assistant.io/t/multifunctional-smart-home-controller-atom-on-esp32/297606/8

# https://devices.esphome.io/devices/Generic-Relay
switch:
  - platform: gpio
    name: "${friendly_name} Plug Relay"
    id: plug_relay_switch
    pin: ${relay_pin}
