substitutions:
  node_name: kitchensinkvolumedial
  friendly_name: Kitchen Sink Volume Dial
  area: Kitchen
  comment: "Volume rotary controller for the Kitchen Sink"
  box_config_file_name: prod_kitchen_sink_volume_dial
  display_rotation: '270'
  receiver_zone_media_player_entity: "media_player.denon_avr_x4300h_zone_3_kitchen"
  # https://github.com/esphome/issues/issues/5265#issuecomment-1867168652
  swap_xy: "true"
  mirror_x: "false"
  mirror_y: "true"

# inspired by https://github.com/RoyalPineapple/esphome/blob/main/m5dial/m5_dial_test.yaml

packages:
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atoms3lite_device.yaml
  logging: !include common/s3_logger.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  albion_volume_dial: !include common/albion_v3_volume_dial.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml
