substitutions:
  node_name: lrcabinetlightstrip
  friendly_name: Living Room Cabinet Light Strip
  area: Living Room
  comment: "This powers a light strip in the living room snack and chocolate cabinet"
  box_config_file_name: prod_living_room_cabinet_light_strip
  choc_light_strip_name: "Chocolate"
  choc_light_strip_id: "chocolate_light_strip"
  choc_light_strip_data_pin: "19"
  choc_light_strip_rmt_channel: "0"
  choc_light_strip_icon: "mdi:led-strip-variant"
  snack_light_strip_name: "Snack"
  snack_light_strip_id: "snack_light_strip"
  snack_light_strip_data_pin: "22"
  snack_light_strip_rmt_channel: "1"
  snack_light_strip_icon: "mdi:led-strip"
  # 26 for 2 long sides and 19 for the short side
  light_strip_num_leds: "71"
  cabinet_light_sensor_update_interval: "1s"
  atom_button_bin: "39"

packages:
  esphome: !include common/default_esphome.yaml
  logging: !include common/default_logger.yaml
#  logging: !include common/debug_logger.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atom_device.yaml
  light: !include { file: common/atom_light.yaml, vars: { light_pin: 27 } }
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml
  i2c_bus: !include common/default_i2c.yaml

sensor:
  - <<: !include { file: common/ambient_light_sensor.yaml, vars: { light_sensor_update_interval: "${cabinet_light_sensor_update_interval}" } }

light:
  - <<: !include { file: common/light_strip.yaml, vars: { led_strip_name: "${choc_light_strip_name}", led_strip_id: "${choc_light_strip_id}", light_data_pin: "${choc_light_strip_data_pin}", rmt_channel: "${choc_light_strip_rmt_channel}", led_strip_icon: "${choc_light_strip_icon}",num_leds: "${light_strip_num_leds}" } }
  - <<: !include { file: common/light_strip.yaml, vars: { led_strip_name: "${snack_light_strip_name}", led_strip_id: "${snack_light_strip_id}", light_data_pin: "${snack_light_strip_data_pin}", rmt_channel: "${snack_light_strip_rmt_channel}", led_strip_icon: "${snack_light_strip_icon}",num_leds: "${light_strip_num_leds}" } }

binary_sensor:
  - platform: gpio
    pin:
      number: ${atom_button_bin}
      inverted: true
    name: "${friendly_name} Button"
    on_release:
      then:
        - logger.log: "${friendly_name} Button tapped"
        - light.toggle: "${choc_light_strip_id}"
        - light.toggle: "${snack_light_strip_id}"
        - logger.log: "Done with ${friendly_name} button tapped!"
