substitutions:
  node_name: kitchen-bluetooth-proxy
  friendly_name: Kitchen Bluetooth Proxy
  area: Kitchen
  comment: "This is a decent iteration"
  box_config_file_name: prod_albion_jukebox_plug

packages:
  esphome: !include common/bt_proxy_esphome.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atom_device.yaml
  light: !include common/atom_light.yaml
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  bluetooth_proxy: !include common/bluetooth_proxy.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
