substitutions:
  node_name: solderingstationbuttons
  friendly_name: Soldering Station Buttons
  area: Dev
  comment: "Not permanently connected"

packages:
  esphome: !include common/default_esphome.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atoms3lite_device.yaml
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  light: !include common/s3_light.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  # Issues with internal_temp on this chip
#  internal_temp: !include common/internal_temp.yaml

# http://10.0.1.104:5000/api/v1/activities/kitchen-lights-on
# http://10.0.1.104:5000/api/v1/activities/kitchen-lights-off
# TODO: maybe set dining room lights to main button?
# http://10.0.1.104:5000/api/v1/activities/custom/soldering/start
# http://10.0.1.104:5000/api/v1/activities/custom/soldering/start

## Device-specific

binary_sensor:
  - platform: gpio
    pin:
      number: 41
      inverted: true
    name: "${friendly_name} Main Button"
    on_press:
      then:
        - logger.log: "Self Button Clicked (maybe turn on lights in dining room?)"
        - logger.log: "Toggle status_led"
        - light.toggle: status_led
        - logger.log: "Done with self button clicked!"
  - platform: gpio
    pin:
      number: 2
      inverted: true
    name: "${friendly_name} Red Button"
    on_press:
      then:
        - logger.log: "Red Button Clicked"
        - logger.log: "Turn on soldering station request"
        - http_request.get:
            url: http://10.0.1.104:5000/api/v1/activities/custom/soldering/start
            headers:
              Content-Type: application/json
            verify_ssl: false
            on_response:
              then:
                - logger.log:
                    format: 'Turn on soldering station activity => Response status: %d, Duration: %u ms'
                    args:
                      - status_code
                      - duration_ms
        - logger.log: "Done with red button turn on soldering station request!"
  - platform: gpio
    pin:
      number: 1
      inverted: true
    name: "${friendly_name} Blue Button"
    on_press:
      then:
        - logger.log: "Blue Button Clicked"
        - logger.log: "Turn off soldering station request"
        - http_request.get:
            url: http://10.0.1.104:5000/api/v1/activities/custom/soldering/stop
            headers:
              Content-Type: application/json
            verify_ssl: false
            on_response:
              then:
                - logger.log:
                    format: 'Turn off soldering station activity => Response status: %d, Duration: %u ms'
                    args:
                      - status_code
                      - duration_ms
        - logger.log: "Done with blue button turn off soldering station request!"
