# Uses the M5Stack Atom Socket
# https://shop.m5stack.com/products/atom-socket-kit-hlw8023-jp-us
# Socket pins:
# G22 - Rx
# G23 - Relay
substitutions:
  node_name: albionjukeboxplug
  friendly_name: AlbionJukebox Plug
  area: JZ Bedroom
  comment: "This is the prototype for the next Burning Man jukebox"
  box_config_file_name: prod_albion_jukebox_plug
  relay_pin: GPIO23
  red_button_pin: "26"
  blue_button_pin: "32"
  media_id: "spotify://playlist/3vu293xS1ylb47xzKYLHTE"
  target_device_entity_id: "media_player.showerspeakerz_upnp_2"

packages:
  esphome: !include common/default_esphome.yaml
  logging: !include common/default_logger.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atom_device.yaml
  light: !include { file: common/atom_light.yaml, vars: { light_pin: 27 } }
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml
  button: !include { file: common/default_atom_button.yaml, vars: { button_pin: 39 } }

## Device-specific

# for power monitoring:
# * https://github.com/esphome/feature-requests/issues/1386
# * https://esphome.io/components/sensor/hlw8012.html
# * https://esphome.io/components/sensor/cse7766.html
# * https://community.home-assistant.io/t/multifunctional-smart-home-controller-atom-on-esp32/297606/8

# https://devices.esphome.io/devices/Generic-Relay
switch:
  - platform: gpio
    name: "${friendly_name} Plug Relay"
    id: plug_relay_switch
    pin: ${relay_pin}

binary_sensor:
  - platform: gpio
    pin:
      number: "${red_button_pin}"
      inverted: true
    name: "${friendly_name} Red Button"
    on_press:
      then:
        - logger.log: "Red Button Clicked started"
        - switch.turn_off: plug_relay_switch
        # https://esphome.io/components/api.html#homeassistant-service-action
        # https://community.home-assistant.io/t/service-calls-through-native-api/374038/2
        - homeassistant.service:
            service: media_player.turn_off
            data:
              entity_id: "${target_device_entity_id}"
        - logger.log: "Red Button Clicked done"

  - platform: gpio
    pin:
      number: "${blue_button_pin}"
      inverted: true
    name: "${friendly_name} Blue Button"
    on_press:
      then:
        - logger.log: "Blue Button Clicked started"
        - switch.turn_on: plug_relay_switch
        # https://esphome.io/components/api.html#homeassistant-service-action
        # https://community.home-assistant.io/t/service-calls-through-native-api/374038/2
        - homeassistant.service:
            service: mass.play_media
            data:
              entity_id: "${target_device_entity_id}"
              media_id: "${media_id}"
              media_type: playlist
        - logger.log: "Blue Button Clicked done"
