substitutions:
  node_name: pantryvolumedial
  friendly_name: Pantry Volume Dial
  area: Pantry
  comment: "Volume rotary controller for the Pantry"
  display_rotation: '270'
  receiver_zone_media_player_entity: "media_player.denon_avr_x4300h_main_zone_living_room"

# inspired by https://github.com/RoyalPineapple/esphome/blob/main/m5dial/m5_dial_test.yaml

packages:
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atoms3lite_device.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
#  internal_temp: !include common/internal_temp.yaml
  albion_volume_dial: !include common/albion_v2_volume_dial.yaml
