# pattern for naming
substitutions:
  node_name: jzdesktempsensor
  friendly_name: JZ Desk Temp Sensor
  area: JZ Bedroom
  comment: "Temperature sensors for inside JZ Desk"
  zeroth_sensor_name: "JZ Desk Tech Cabinet Router Shelf"
  first_sensor_name: "JZ Desk Tech Cabinet UPS Shelf"
  second_sensor_name: "JZ Desk Tech Cabinet NUC Shelf"
  oversampling_value: "16x"
  update_interval_value: "60s"
  sht_address: "0x44"
  bmp_address: "0x76"

packages:
  esphome: !include common/default_esphome.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atom_device.yaml
  light: !include common/atom_light.yaml
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml

# temp sensors

# https://esphome.io/components/i2c#i2c
i2c:
  - id: grove
    sda: GPIO26
    scl: GPIO32
    scan: true

# https://esphome.io/components/tca9548a
tca9548a:
  - address: 0x70
    id: multiplex0
    i2c_id: grove
    channels:
      - bus_id: multiplex0channel0
        channel: 0
      - bus_id: multiplex0channel1
        channel: 1
      - bus_id: multiplex0channel2
        channel: 2

sensor:
  # https://esphome.io/components/sensor/sht4x.html
  - platform: sht4x
    i2c_id: multiplex0channel0
    address: ${sht_address}
    temperature:
      name: "${zeroth_sensor_name} Temperature"
    humidity:
      name: "${zeroth_sensor_name} Relative Humidity"
  # https://esphome.io/components/sensor/bmp280.html
  - platform: bmp280
    i2c_id: multiplex0channel0
    temperature:
      name: "${zeroth_sensor_name} Outside Temperature"
      oversampling: ${oversampling_value}
    pressure:
      name: "${zeroth_sensor_name} Outside Pressure"
    address: ${bmp_address}
    update_interval: ${update_interval_value}
  # https://esphome.io/components/sensor/sht4x.html
  - platform: sht4x
    i2c_id: multiplex0channel1
    address: ${sht_address}
    temperature:
      name: "${first_sensor_name} Temperature"
    humidity:
      name: "${first_sensor_name} Relative Humidity"
  # https://esphome.io/components/sensor/bmp280.html
  - platform: bmp280
    i2c_id: multiplex0channel1
    temperature:
      name: "${first_sensor_name} Outside Temperature"
      oversampling: ${oversampling_value}
    pressure:
      name: "${first_sensor_name} Outside Pressure"
    address: ${bmp_address}
    update_interval: ${update_interval_value}
  # https://esphome.io/components/sensor/sht4x.html
  - platform: sht4x
    i2c_id: multiplex0channel2
    address: ${sht_address}
    temperature:
      name: "${second_sensor_name} Temperature"
    humidity:
      name: "${second_sensor_name} Relative Humidity"
  # https://esphome.io/components/sensor/bmp280.html
  - platform: bmp280
    i2c_id: multiplex0channel2
    temperature:
      name: "${second_sensor_name} Outside Temperature"
      oversampling: ${oversampling_value}
    pressure:
      name: "${second_sensor_name} Outside Pressure"
    address: ${bmp_address}
    update_interval: ${update_interval_value}

## Device-specific

binary_sensor:
  - platform: gpio
    pin:
      number: 39
      inverted: true
    name: "${friendly_name} Button"
    on_release:
      then:
        - logger.log: "Button tapped"
        - logger.log: "Done with button tapped!"
