substitutions:
  node_name: fullbathwindowenvsensor
  friendly_name: Full Bath Window Env Sensor
  area: Full Bath
  comment: "This goes by the window (coldest place in the room)"
  box_config_file_name: prod_full_bath_window_env_sensor

packages:
  esphome: !include common/default_esphome.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atom_device.yaml
  light: !include common/atom_light.yaml
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  env_pro_sensor: !include common/env_pro_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml

# env sensors

# https://esphome.io/components/i2c#i2c
i2c:
  - id: grove
    sda: GPIO26
    scl: GPIO32
    scan: true

## Device-specific

binary_sensor:
  - platform: gpio
    pin:
      number: 39
      inverted: true
    name: "${friendly_name} Button"
    on_release:
      then:
        - logger.log: "Start request"
        - logger.log: "Done with request now skip any delay!"
