substitutions:
  node_name: jzvornadoblaster
  friendly_name: JZ Vornado IR Blaster
  area: JZ Bedroom
  comment: "Controlling the Vornado window fan in JZ Bedroom via IR"
  box_config_file_name: prod_jz_vornado_controller
  remote_transmitter_pin: "GPIO26"
  vornado_restore_mode: RESTORE_DEFAULT_OFF
  repeat_times: "3"
  repeat_wait_time: "7ms"
  carrier_frequencey: "38000"

# use `dev_ir_receiver_logger.yaml` to grab IR codes

packages:
  esphome: !include common/default_esphome.yaml
#  logging: !include common/default_logger.yaml
  logging: !include common/debug_logger.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atom_device.yaml
  light: !include { file: common/atom_light.yaml, vars: { light_pin: 27 } }
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml

## Device-specific
# https://esphome.io/guides/setting_up_rmt_devices#remote-setting-up-infrared
# https://docs.m5stack.com/en/unit/ir
# https://github.com/Chill-Division/M5Stack-ESPHome/blob/main/Mini%20Infrared%20Emitter%20%26%20Receiver%20Unit.md
# https://www.reddit.com/r/arduino/comments/xtyoq2/unknown_ir_protocol/
# https://github.com/elementcarbon12/vornado_transom_remote_test/blob/main/vornado_transom_remote_test.ino

remote_transmitter:
  pin: "${remote_transmitter_pin}"
  carrier_duty_percent: 50%

# https://esphome.io/components/script.html
script:
  - id: send_on_off_ir_blast
    then:
      - remote_transmitter.transmit_raw:
          code: [ 1250, -436, 1250, -435, 405, -1281, 1250, -436, 1249, -436, 405, -1280, 405, -1281, 405, -1281, 405, -1281, 1250, -436, 405, -1279, 405, -8129, 1252, -435, 1250, -436, 405, -1279, 1251, -436, 1250, -435, 405, -1280, 406, -1281, 405, -1280,
                  405, -1281, 1251, -435, 404, -1281, 405, -8128, 1251, -436, 1249, -436, 405, -1280, 1251, -435, 1250, -435, 405, -1281, 405, -1281, 404, -1281, 405, -1281, 1250, -436, 404, -1280, 406, -8127, 1251, -436, 1249, -436, 404, -1281, 1250, -436, 1249, -436,
                  405, -1280, 405, -1281, 405, -1281, 405, -1280, 1251, -435, 405, -1280, 405, -8129, 1251, -436, 1250, -436, 404, -1281, 1250, -436, 1249, -437, 404, -1280, 405, -1281, 404, -1281, 405, -1281, 1249, -437, 404, -1281, 405, -8128, 1251, -435, 1249, -437,
                  404, -1281, 1250, -436, 1250, -436, 404, -1280, 405, -1281, 405, -1280, 405, -1281, 1250, -436, 404, -1280, 406 ]
          carrier_frequency: "${carrier_frequencey}"
          repeat:
            times: "${repeat_times}"
            wait_time: "${repeat_wait_time}"
  - id: send_change_direction_ir_blast
    then:
      - remote_transmitter.transmit_raw:
          code: [ 1271, -416, 1269, -417, 423, -1260, 1270, -417, 1268, -416, 424, -1261, 424, -1261, 425, -1262, 423, -1262, 424, -1263, 423, -1261, 1269, -7265, 1270, -417, 1268, -417, 424, -1262, 1269, -418, 1268, -418, 423, -1261, 424, -1264, 422, -1263,
                  423, -1262, 424, -1262, 424, -1262, 1269, -7263, 1270, -418, 1268, -418, 422, -1261, 1269, -418, 1267, -419, 421, -1263, 423, -1263, 423, -1261, 424, -1263, 401, -1284, 423, -1262, 1269, -7264, 1248, -440, 1265, -420, 420, -1265, 1247, -440, 1245,
                  -439, 401, -1284, 423, -1264, 421, -1264, 402, -1283, 402, -1285, 401, -1283, 1247, -7285, 1269, -419, 1247, -438, 402, -1283, 1247, -439, 1246, -440, 400, -1284, 402, -1284, 402, -1283, 403, -1283, 402, -1284, 402, -1285, 1247, -7286, 1249, -439,
                  1246, -439, 401, -1284, 1247, -438, 1247, -439, 401, -1284, 402, -1284, 402, -1285, 401, -1283, 403, -1284, 401, -1284, 1247, -7285, 1269, -418, 1266, -444, 376, -1284, 1266, -420, 1266, -419, 400, -1285, 423, -1263, 423, -1262, 423, -1263, 422, -1264,
                  422, -1263, 1268 ]
          carrier_frequency: "${carrier_frequencey}"
          repeat:
            times: "${repeat_times}"
            wait_time: "${repeat_wait_time}"
  - id: send_increase_fans_ir_blast
    then:
      - remote_transmitter.transmit_raw:
          code: [ 1271, -417, 1268, -417, 423, -1261, 1270, -417, 1269, -415, 1270, -418, 422, -1262, 424, -1262, 424, -1262, 1269, -442, 1244, -417, 424, -8109, 1272, -416, 1270, -417, 423, -1261, 1270, -441, 1244, -418, 1268, -441, 399, -1262, 424, -1261,
                  424, -1263, 1269, -417, 1268, -417, 423, -8109, 1270, -418, 1268, -417, 423, -1261, 1270, -417, 1268, -416, 1270, -416, 424, -1262, 424, -1261, 424, -1260, 1270, -418, 1267, -418, 423, -8109, 1270, -419, 1267, -419, 422, -1261, 1269, -418, 1267, -417,
                  1269, -441, 399, -1261, 424, -1261, 424, -1262, 1268, -418, 1267, -417, 422, -8108, 1269, -418, 1267, -417, 423, -1262, 1268, -418, 1267, -442, 1242, -419, 422, -1261, 423, -1262, 424, -1262, 1268, -419, 1267, -418, 422, -8108, 1270, -418, 1267, -419,
                  422, -1261, 1269, -420, 1265, -418, 1268, -418, 422, -1262, 424, -1261, 424, -1262, 1268, -419, 1267, -418, 422 ]
          carrier_frequency: "${carrier_frequencey}"
          repeat:
            times: "${repeat_times}"
            wait_time: "${repeat_wait_time}"
  - id: send_decrease_fans_ir_blast
    then:
      - remote_transmitter.transmit_raw:
          code: [ 1270, -417, 1269, -442, 398, -1262, 1269, -442, 1244, -442, 398, -1262, 424, -1262, 424, -1262, 424, -1262, 424, -1261, 1269, -443, 398, -8108, 1272, -417, 1269, -442, 398, -1262, 1270, -442, 1243, -442, 398, -1260, 426, -1261, 425, -1261,
                  424, -1261, 424, -1262, 1268, -442, 398, -8106, 1271, -442, 1243, -442, 398, -1262, 1268, -443, 1242, -417, 424, -1261, 425, -1261, 424, -1260, 425, -1261, 425, -1262, 1268, -418, 422, -8108, 1271, -442, 1243, -442, 398, -1262, 1268, -418, 1268, -442,
                  398, -1262, 423, -1262, 424, -1261, 424, -1261, 425, -1262, 1267, -418, 423, -8106, 1271, -417, 1269, -419, 421, -1261, 1269, -443, 1243, -442, 398, -1261, 424, -1261, 424, -1261, 424, -1262, 423, -1263, 1267, -443, 398, -8106, 1271, -442, 1242, -419,
                  422, -1261, 1268, -443, 1242, -443, 397, -1262, 423, -1263, 423, -1263, 422, -1261, 424, -1262, 1268, -443, 397 ]
          carrier_frequency: "${carrier_frequencey}"
          repeat:
            times: "${repeat_times}"
            wait_time: "${repeat_wait_time}"

# https://esphome.io/components/button/index.html
button:
  - platform: template
    name: "${friendly_name} On/Off"
    id: transmit_on_off_blast
    icon: "mdi:light-switch"
    on_press:
      - logger.log: "${friendly_name} on/off pressed"
      - script.execute: send_on_off_ir_blast
  - platform: template
    name: "${friendly_name} Change Direction"
    id: transmit_change_direction_blast
    icon: "mdi:light-switch"
    on_press:
      - logger.log: "${friendly_name} change direction pressed"
      - script.execute: send_change_direction_ir_blast
  - platform: template
    name: "${friendly_name} Increase Fans"
    id: transmit_increase_fans_blast
    icon: "mdi:light-switch"
    on_press:
      - logger.log: "${friendly_name} increase fans pressed"
      - script.execute: send_increase_fans_ir_blast
  - platform: template
    name: "${friendly_name} Decrease Fans"
    id: transmit_decrease_fans_blast
    icon: "mdi:light-switch"
    on_press:
      - logger.log: "${friendly_name} decrease fans pressed"
      - script.execute: send_decrease_fans_ir_blast

# https://esphome.io/components/switch/template
switch:
  - platform: template
    name: ${friendly_name} Power Tx Switch
    id: "ir_tx_power_button"
    restore_mode: ${vornado_restore_mode}
    optimistic: true
    assumed_state: true
    turn_on_action:
      - script.execute: send_on_off_ir_blast
    turn_off_action:
      - script.execute: send_on_off_ir_blast

## TODO: consider disabling and replacing with default button
binary_sensor:
  - platform: gpio
    pin:
      number: 39
    name: ${friendly_name} IR Transmitter Button
    on_press:
      then:
        - logger.log: "Transmitter button press started"
        - logger.log: "Transmit IR rc_switch code"
        - switch.toggle: ir_tx_power_button
        - logger.log: "Done with transmitter button pressed!"
