substitutions:
  node_name: fullbathshowerspeakerz
  friendly_name: Full Bath Shower Speakerz
  area: Full Bath
  comment: "For controlling the ShowerSpeakerz and bluetooth music"
  box_config_file_name: prod_full_bath_shower_speakerz_buttons
  rufus_url: !secret rufus_url

packages:
  esphome: !include common/default_esphome.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atoms3lite_device.yaml
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  light: !include { file: common/atom_light.yaml, vars: { light_pin: 35 } }
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml
  internal_temp: !include common/internal_temp.yaml
  button: !include { file: common/default_atom_button.yaml, vars: { button_pin: 41 } }

# ${rufus_url}/api/v1/activities/kitchen-lights-on
# ${rufus_url}/api/v1/activities/kitchen-lights-off
# ${rufus_url}/api/v1/activities/full-bath-music-lights
# ${rufus_url}/api/v1/activities/full-bath-music-lights-off

## Device-specific

binary_sensor:
  - platform: gpio
    pin:
      number: 2
      inverted: true
    name: "${friendly_name} Red Button"
    on_press:
      then:
        - logger.log: "Red Button Clicked"
        - logger.log: "Turn off full bath music lights request"
        - http_request.get:
            url: ${rufus_url}/api/v1/activities/full-bath-music-lights-off
            headers:
              Content-Type: application/json
            verify_ssl: false
            on_response:
              then:
                - logger.log:
                    format: 'Turn off full bath music lights activity => Response status: %d, Duration: %u ms'
                    args:
                      - status_code
                      - duration_ms
        - logger.log: "Done with red button turn off full bath music lights request!"
  - platform: gpio
    pin:
      number: 1
      inverted: true
    name: "${friendly_name} Blue Button"
    on_press:
      then:
        - logger.log: "Blue Button Clicked"
        - logger.log: "Turn on full bath music lights request"
        - http_request.get:
            url: ${rufus_url}/api/v1/activities/full-bath-music-lights
            headers:
              Content-Type: application/json
            verify_ssl: false
            on_response:
              then:
                - logger.log:
                    format: 'Turn on full bath music lights activity => Response status: %d, Duration: %u ms'
                    args:
                      - status_code
                      - duration_ms
        - logger.log: "Done with blue button turn on full bath music lights request!"
