substitutions:
  node_name: fbshowerspeakerzv4
  friendly_name: Full Bath ShowerSpeakerz V4
  area: Full Bath
  comment: "For controlling the ShowerSpeakerz direct playing playlists to them"
  box_config_file_name: prod_full_bath_shower_speakerz_buttons_v4

packages:
  esphome: !include common/default_esphome.yaml
  logging: !include common/s3_logger.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atoms3lite_device.yaml
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  light: !include { file: common/atom_light.yaml, vars: { light_pin: 35 } }
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml
  internal_temp: !include common/internal_temp.yaml
  button: !include { file: common/default_atom_button.yaml, vars: { button_pin: 41 } }

# ${rufus_url}/api/v1/activities/kitchen-lights-on
# ${rufus_url}/api/v1/activities/kitchen-lights-off
# ${rufus_url}/api/v1/activities/full-bath-music-lights
# ${rufus_url}/api/v1/activities/full-bath-music-lights-off

## Device-specific

binary_sensor:
  - platform: gpio
    pin:
      number: 2
      inverted: true
    name: "${friendly_name} Red Button"
    on_press:
      then:
        - logger.log: "Red Button Clicked started"
        # https://esphome.io/components/api#homeassistant-event-action
        - homeassistant.event:
            event: esphome.shower_speakerz_red_button_pressed
#            event: esphome.button_pressed
            data:
              message: Button was pressed
        - logger.log: "Red Button Clicked done"

  - platform: gpio
    pin:
      number: 1
      inverted: true
    name: "${friendly_name} Blue Button"
    on_press:
      then:
        - logger.log: "Blue Button Clicked started"
        # https://esphome.io/components/api#homeassistant-event-action
        - homeassistant.event:
            event: esphome.shower_speakerz_blue_button_pressed
#            event: esphome.button_pressed
            data:
              message: Button was pressed
        - logger.log: "Blue Button Clicked done"
