# Uses the M5Stack Atom Socket
# https://shop.m5stack.com/products/atom-socket-kit-hlw8023-jp-us
# Socket pins:
# G22 - Rx
# G23 - Relay
substitutions:
  node_name: fbshowerspeakerzplugv1
  friendly_name: ShowerSpeakerz Plug V1
  area: Full Bath
  comment: "This is the next ShowerSpeakerz as a combined unit"
  box_config_file_name: prod_full_bath_shower_speakerz_plug_v1
  rufus_url: !secret rufus_url
  relay_pin: GPIO23
  red_button_pin: "26"
  blue_button_pin: "32"
  target_device_entity_id: "media_player.showerspeakerz_upnp_3"
  primary_media_id: "spotify://album/2AlPRfYeskAMxhJS00xjeP"
  primary_media_type: "album"

packages:
  esphome: !include common/default_esphome.yaml
  logging: !include common/default_logger.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atom_device.yaml
  light: !include { file: common/atom_light.yaml, vars: { light_pin: 27 } }
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml
  button: !include { file: common/default_atom_button.yaml, vars: { button_pin: 39 } }
  rufus_activity_request: !include common/rufus_activity_request.yaml

## Device-specific

# for power monitoring:
# * https://github.com/esphome/feature-requests/issues/1386
# * https://esphome.io/components/sensor/hlw8012.html
# * https://esphome.io/components/sensor/cse7766.html
# * https://community.home-assistant.io/t/multifunctional-smart-home-controller-atom-on-esp32/297606/8

text_sensor:
  # https://esphome.io/components/text_sensor/homeassistant.html
  - platform: homeassistant
    name: "${friendly_name} Media Type"
    id: media_type_text_sensor
    entity_id: input_text.showerspeakerz_media_type
  # https://esphome.io/components/text_sensor/homeassistant.html
  - platform: homeassistant
    name: "${friendly_name} Media ID"
    id: media_id_text_sensor
    entity_id: input_text.showerspeakerz_media_id

# https://devices.esphome.io/devices/Generic-Relay
switch:
  - platform: gpio
    name: "${friendly_name} Plug Relay"
    id: plug_relay_switch
    pin: ${relay_pin}

binary_sensor:
  - platform: gpio
    pin:
      number: "${red_button_pin}"
      inverted: true
    name: "${friendly_name} Red Button"
    on_press:
      then:
        - logger.log: "Red Button Clicked started"
        - switch.turn_off: plug_relay_switch
        - script.execute:
            id: rufus_activity_request
            rufus_url: "${rufus_url}"
            activity: "full-bath-music-lights-off"
        # https://esphome.io/components/api.html#homeassistant-service-action
        # https://community.home-assistant.io/t/service-calls-through-native-api/374038/2
        - homeassistant.service:
            service: media_player.turn_off
            data:
              entity_id: "${target_device_entity_id}"
        - logger.log: "Red Button Clicked done"

  - platform: gpio
    pin:
      number: "${blue_button_pin}"
      inverted: true
    name: "${friendly_name} Blue Button"
    # https://esphome.io/components/binary_sensor/index.html#on-multi-click
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Blue => Double Clicked"
          - logger.log: "Blue Button Double Clicked started"
          - switch.turn_on: plug_relay_switch
          - script.execute:
              id: rufus_activity_request
              rufus_url: "${rufus_url}"
              activity: "full-bath-music-lights"
          # https://esphome.io/components/api.html#homeassistant-service-action
          # https://community.home-assistant.io/t/service-calls-through-native-api/374038/2
          - homeassistant.service:
              service: mass.play_media
              data_template:
                entity_id: "${target_device_entity_id}"
                media_id: "{{ my_media_id }}"
                media_type: "{{ my_media_type }}"
              variables:
                my_media_id: |-
                  return id(media_id_text_sensor).state;
                my_media_type: |-
                  return id(media_type_text_sensor).state;
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - logger.log: "Blue => Single Long Clicked"
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Blue => Single Short Clicked"
          - logger.log: "Blue Button Clicked started"
          - switch.turn_on: plug_relay_switch
          - script.execute:
              id: rufus_activity_request
              rufus_url: "${rufus_url}"
              activity: "full-bath-music-lights"
          - logger.log: "Blue Button Clicked done"
