substitutions:
  node_name: lrcabinetlightstrip
  friendly_name: Living Room Cabinet Light Strip
  area: Living Room
  comment: "This powers a light strip in the living room snack and chocolate cabinet"
  box_config_file_name: prod_living_room_cabinet_light_strip
  choc_light_strip_name: "Chocolate"
  choc_light_strip_id: "chocolate_light_strip"
  choc_light_strip_data_pin: "22"
  snack_light_strip_name: "Snack"
  snack_light_strip_id: "snack_light_strip"
  snack_light_strip_data_pin: "23"
#  light_strip_data_pin: "26"
  # 26 for 2 long sides and 19 for the short side
  light_strip_num_leds: "71"
  cabinet_light_sensor_update_interval: "1s"

packages:
  esphome: !include common/default_esphome.yaml
#  logging: !include common/default_logger.yaml
  logging: !include common/debug_logger.yaml
  wifi: !include common/wifi.yaml
  esp32: !include common/m5atom_device.yaml
  light: !include { file: common/atom_light.yaml, vars: { light_pin: 27 } }
  reset_button: !include common/reset_button.yaml
  networking: !include common/networking.yaml
  http: !include common/http.yaml
  version: !include common/version.yaml
  wifi_info: !include common/wifi_info.yaml
  uptime: !include common/uptime.yaml
  wifi_signal_sensor: !include common/wifi_signal_sensor.yaml
  status_sensor: !include common/status_sensor.yaml
  internal_temp: !include common/internal_temp.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
  albion_boxes_info: !include common/albionboxes_info.yaml
  button: !include { file: common/default_atom_button.yaml, vars: { button_pin: 39 } }
  choc_light_strip: !include { file: common/light_strip.yaml, vars: { led_strip_name: "${choc_light_strip_name}", led_strip_id: "${choc_light_strip_id}", light_data_pin: "${choc_light_strip_data_pin}", num_leds: "${light_strip_num_leds}" } }
#  snack_light_strip: !include { file: common/light_strip.yaml, vars: { led_strip_name: "${snack_light_strip_name}", led_strip_id: "${snack_light_strip_id}", light_data_pin: "${snack_light_strip_data_pin}", num_leds: "${light_strip_num_leds}" } }
  i2c_bus: !include common/default_i2c.yaml

sensor:
  - <<: !include { file: common/ambient_light_sensor.yaml, vars: { light_sensor_update_interval: "${cabinet_light_sensor_update_interval}" } }
