# Main docs here:
# https://shop.m5stack.com/products/m5stack-dial-esp32-s3-smart-rotary-knob-w-1-28-round-touch-screen
# inspired by https://github.com/RoyalPineapple/esphome/blob/main/m5dial/m5_dial_test.yaml
# https://community.home-assistant.io/t/m5stack-dial-esp32-s3-smart-rotary-knob/623518/14

# https://github.com/esphome/issues/issues/5427
# https://esphome.io/guides/faq#why-am-i-getting-a-warning-about-strapping-pins

# Inspired by https://github.com/RoyalPineapple/esphome/blob/main/m5dial/m5_dial_test.yaml

## Device-specific

# FIXME: collapse into existing default_esphome.yaml
esphome:
  name: ${node_name}
  # for more on friendly_name issues, see https://github.com/jzucker2/goober/blob/master/notes/ESPHOME.md
#  friendly_name: ${friendly_name}
  area: ${area}
  comment: ${comment}
  project: !include default_project.yaml
  on_boot:
    then:
      - light.turn_on: backlight

packages:
  colors: !include ./dial/dial_colors.yaml
  internal_ic2: !include ./dial/dial_internal_i2c.yaml
  fonts: !include ./dial/dial_fonts.yaml
  images: !include ./dial/dial_images.yaml
  spi: !include ./dial/dial_spi.yaml
  uart: !include ./dial/dial_uart.yaml
  dial_speaker: !include ./dial/dial_speaker.yaml
  volume_set_script: !include ./dial/scripts/hass_zone_volume_set_script.yaml

# https://esphome.io/guides/automations.html#global-variables
globals:
  - id: light_brightness_value
    type: int
    initial_value: '0'
    restore_value: yes
  - id: media_volume_value
    type: float
    initial_value: '0.0'
    restore_value: yes
  - id: volume_encoder_resolution
    type: int
    initial_value: '1'
    restore_value: yes
  - id: selected_color
    type: Color
    initial_value: very_dark_blue
    restore_value: no

sensor:
  - <<: !include ./dial/rotary_encoder/dial_simple_volume_rotary_encoder.yaml
  - <<: !include ./dial/dial_hass_volume_sensor.yaml

light:
  - <<: !include ./dial/dial_backlight_light.yaml

output:
  - <<: !include ./dial/dial_backlight_output.yaml
  - <<: !include ./dial/dial_speaker_output.yaml

display:
  - <<: !include ./dial/display/dial_default_display.yaml

binary_sensor:
  - <<: !include ./dial/dial_button.yaml
