esphome:
  name: ${node_name}
  # for more on friendly_name issues, see https://github.com/jzucker2/goober/blob/master/notes/ESPHOME.md
#  friendly_name: ${friendly_name}
  area: ${area}
  comment: ${comment}
  # https://esphome.io/components/esphome#project-information
  project:
    name: "jordan.albionboxes"
    # FIXME: make an env var to be shared
    version: "0.1.0"
#    name: m5stack.atom-echo
#    version: "1.0"
