- platform: touchscreen
  name: "${friendly_name} Volume Screen Zone State Button"
  page_id: VolumePage
  x_min: 70
  x_max: 170
  y_min: 70
  y_max: 170
  on_release:
    then:
      - lambda: |-
          ESP_LOGD("media_player_zone_state", "touched zone power state button");
      - script.execute:
          id: hass_zone_power_set
          entity_id: "${receiver_zone_media_player_entity}"
          media_zone_state: !lambda 'return id(media_zone_state).state;'
#      - if:
#          condition:
#            # Should return either true or false
#            lambda: |-
#              return ( id(media_zone_state).state == "off" || id(media_zone_state).state == "standby" );
#          then:
#            - homeassistant.service:
#                service: media_player.turn_on
#                data:
#                  entity_id: ${receiver_zone_media_player_entity}
#          else:
#            - homeassistant.service:
#                service: media_player.turn_off
#                data:
#                  entity_id: ${receiver_zone_media_player_entity}
      - lambda: |-
          ESP_LOGD("media_player_zone_state", "after hass power state action");
